# Generated by Cascade assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_alter_orderitem_product_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(max_length=20, blank=True),
        ),
    ]
