# Generated by Django 5.2.4 on 2025-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Banner title (e.g., 'New Summer Collection')", max_length=200)),
                ('description', models.TextField(help_text='Banner description or tagline', max_length=500)),
                ('image', models.ImageField(help_text='Banner image (recommended: 1920x600px)', upload_to='banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on the website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('animation_type', models.CharField(choices=[('fade', 'Fade In/Out'), ('slide-left', 'Slide from Left'), ('slide-right', 'Slide from Right'), ('slide-up', 'Slide from Bottom'), ('slide-down', 'Slide from Top'), ('zoom', 'Zoom In'), ('bounce', 'Bounce In')], default='fade', max_length=20)),
                ('animation_duration', models.PositiveIntegerField(default=3000, help_text='Animation duration in milliseconds')),
                ('link_url', models.URLField(blank=True, help_text='Optional link when banner is clicked', null=True)),
                ('link_text', models.CharField(blank=True, help_text="Button text (e.g., 'Shop Now')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
