# Generated by Django 5.2.4 on 2025-08-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_populate_sizes'),
        ('products', '0002_product_available_colors_alter_category_image'),
    ]

    operations = [
    ]
